name: cotta
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - appdirs==1.4.4
    - attr==0.3.1
    - attrs==21.2.0
    - backcall==0.2.0
    - black==19.3b0
    - chardet==3.0.4
    - click==8.0.3
    - cloudpickle==2.0.0
    - decorator==5.1.0
    - flake8==4.0.1
    - idna==2.10
    - imagecorruptions==1.1.2
    - imageio==2.10.1
    - iopath==0.1.9
    - ipython==7.28.0
    - isort==4.3.21
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.1.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - networkx==2.6.3
    - numpy==1.19.5
    - packaging==21.0
    - parameterized==0.8.1
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - portalocker==2.3.2
    - prompt-toolkit==3.0.21
    - ptyprocess==0.7.0
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pygments==2.10.0
    - pytorchcv==0.0.67
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==6.0
    - requests==2.23.0
    - git+https://github.com/robustbench/robustbench@v0.1#egg=robustbench
    - scikit-image==0.18.3
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - simplejson==3.17.5
    - submitit==1.4.0
    - threadpoolctl==3.0.0
    - tifffile==2021.10.12
    - timm==0.4.12
    - toml==0.10.2
    - tqdm==4.56.2
    - traitlets==5.1.0
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - yacs==0.1.8
    - yapf==0.31.0
    - yattag==1.14.0
    - gdown==5.1.0
